// WEB D/MERN/React/react-project/src/components/Hero.jsx
const Hero = (props) => {
  return (
    <>
      <section className="bg-indigo-700 py-20 mb-4">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col items-center">
          <div className="text-center">
            <h1 className="text-4xl font-extrabold text-white sm:text-5xl md:text-6xl">
              Become a React Dev
              {/* {props.title  } */}
            </h1>
            <p className="my-4 text-xl text-white">
              Find the React job that fits your skills and needs
            </p>
          </div>
        </div>
      </section>
    </>
  );
};

export default Hero;

// WEB D/Vue/vue-crash/src/components/Hero.vue
   <script setup>

import { defineProps } from 'vue';

defineProps({
    title: {
        type: String,
        default: 'Become a Vue Dev',
    },
    subtitle: {
        type: String,
        default: 'Find the VueFind the Vue job that fits your skills and needs',
    }
});

</script>




<template>

    <section class="bg-green-700 py-20 mb-4">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col items-center">
            <div class="text-center">
                <h1 class="text-4xl font-extrabold text-white sm:text-5xl md:text-6xl">

                    {{ title }}
                </h1>
                <p class="my-4 text-xl text-white">
                    {{ subtitle }}

                </p>
            </div>
        </div>
    </section>


</template>
