// WEB D/MERN/React/react-project/src/components/Navbar.jsx
import { NavLink } from "react-router-dom";

import logo from "../assets/images/logo.png";

function Navbar() {
  const linkClass = ({ isActive }) =>
    isActive
      ? "text-white bg-black hover:bg-gray-900 hover:text-white rounded-md px-3 py-2"
      : "text-white  hover:bg-gray-900 hover:text-white rounded-md px-3 py-2";
  return (
    <>
      <nav className="bg-indigo-700 border-b border-indigo-500">
        <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
          <div className="flex h-20 items-center justify-between">
            <div className="flex flex-1 items-center justify-center md:items-stretch md:justify-start">
              <NavLink className="flex flex-shrink-0 items-center mr-4" to="/">
                <img className="h-10 w-auto" src={logo} alt="React Jobs" />
                <span className="hidden md:block text-white text-2xl font-bold ml-2">
                  React Jobs
                </span>
              </NavLink>
              <div className="md:ml-auto">
                <div className="flex space-x-2">
                  <NavLink
                    to="/"
                    className={linkClass}
                    // className="text-white bg-black hover:bg-gray-900 hover:text-white rounded-md px-3 py-2"
                  >
                    Home
                  </NavLink>
                  <NavLink
                    to="/jobs"
                    className={linkClass}
                  >
                    Jobs
                  </NavLink>
                  <NavLink
                    to="/addjob"
                    className={linkClass}
                  >
                    Add Job
                  </NavLink>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </>
  );
}

export default Navbar;

// WEB D/Vue/vue-crash/src/components/Navbar.vue
<script setup>

import logo from '@/assets/img/logo.png';
import { RouterLink, useRoute } from 'vue-router';


const isActiveLink = (routePath) => {
    const route = useRoute();
    return route.path === routePath;

}
</script>

<template>
    <nav class="bg-green-700 border-b border-green-500">
        <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="flex h-20 items-center justify-between">
                <div class="flex flex-1 items-center justify-center md:items-stretch md:justify-start">
                    <!-- Logo -->
                    <RouterLink class="flex flex-shrink-0 items-center mr-4" to="/">
                        <img class="h-10 w-auto" :src="logo" alt="Vue Jobs" />
                        <span class="hidden md:block text-white text-2xl font-bold ml-2">Vue Jobs</span>
                    </RouterLink>
                    <div class="md:ml-auto">
                        <div class="flex space-x-2">
                            <RouterLink to="/"
                                :class="[isActiveLink('/') ? 'bg-green-900' : ' hover:bg-gray-900 hover:text-white', 'text-white', 'rounded-md', 'px-3', 'py-2']">
                                Home</RouterLink>
                            <RouterLink to="/jobs"
                                :class="[isActiveLink('/jobs') ? 'bg-green-900' : ' hover:bg-gray-900 hover:text-white', 'text-white', 'rounded-md', 'px-3', 'py-2']">
                                Jobs
                            </RouterLink>
                            <RouterLink to="/jobs/add"
                                :class="[isActiveLink('/jobs/add') ? 'bg-green-900' : ' hover:bg-gray-900 hover:text-white', 'text-white', 'rounded-md', 'px-3', 'py-2']">
                                Add
                                Job</RouterLink>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>


</template>
